# -*- coding: utf-8 -*-
"""11의 사본

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1EJFdQEDPTDugSHVHOgxEoH219xyrz96k
"""

import requests
from bs4 import BeautifulSoup

def return_value(address):
    res = requests.get(address)
    soup = BeautifulSoup(res.content, 'html.parser')

    section = soup.find('tbody')
    items = section.find_all('tr', onmouseover="mouseOver(this)")
    for item in items:
        basic_info = item.get_text()
        sinfo = basic_info.split("\n")
        print("\t" + sinfo[1] + "\t\t" + sinfo[2] + "\t\t\t" + sinfo[3])


baseaddress = 'https://finance.naver.com/sise/sise_market_sum.naver?&page='
for i in range(1,2):
    return_value(baseaddress+str(i))

import requests
from bs4 import BeautifulSoup
import csv
rawData = []
dataForCsv = []

f = open('/content/drive/MyDrive/Colab Notebooks/stock.csv', 'wt', encoding='utf-8')
wr = csv.writer(f)


def return_value(address):
    res = requests.get(address)
    soup = BeautifulSoup(res.content, 'html.parser')

    section = soup.find('tbody')
    items = section.find_all('tr', onmouseover="mouseOver(this)")
    for item in items:
        basic_info = item.get_text()
        sinfo = basic_info.split("\n")
        for i in range(1, 4):
          rawData.append(sinfo[i])



baseaddress = 'https://finance.naver.com/sise/sise_market_sum.naver?&page='

for i in range(1,2):
    return_value(baseaddress+str(i))

dataForCsv = [rawData[i * 3:(i + 1) * 3] for i in range((len(rawData) + 3 - 1) // 3 )] 

for i in range(0, 50):
  wr.writerow(dataForCsv[i])